# Generated by Django 5.0.1 on 2024-01-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdb',
            name='CreditNo',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdb',
            name='Phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
