# Generated by Django 5.0.1 on 2024-01-22 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backent', '0002_alter_productdb_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backent.categorydb'),
        ),
    ]
