# Generated by Django 5.0.1 on 2024-01-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backent', '0003_alter_productdb_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productdb',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
